name: Build with Nix

on:
  push:
    branches:
      - master
  pull_request:

## Build ##

jobs:
  build:
    name: Build with Nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix cache
        uses: cachix/cachix-action@v14
        with:
          name: dpsim
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build dpsim
        run: nix build .#dpsim
