name: Publish DPsim package to Python Package Index (PyPI)

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-publish-sdist:
    name: Build DPsim source distribution and publish to PyPi
    runs-on: ubuntu-latest
    container: sogno/dpsim:dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build DPsim source distribution
      shell: bash
      run: python3 -m build --sdist --outdir dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  build-and-publish-wheels:
    name: Build DPsim wheels and publish to PyPI
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build DPsim wheels for all supported Python versions
      uses: pypa/cibuildwheel@v2.23.2
      with:
        output-dir: dist

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}